"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.exampleRoutes = void 0;
const express_1 = require("express");
const example_controllers_1 = require("../controllers/example.controllers");
const exampleRoutes = (0, express_1.Router)();
exports.exampleRoutes = exampleRoutes;
const examplelController = new example_controllers_1.ExampleController();
exampleRoutes.get("/hello-type", examplelController.example);
exampleRoutes.get("/teste-error", examplelController.testError);
