"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.routes = void 0;
const express_1 = require("express");
const example_routes_1 = require("./example.routes");
const user_routes_1 = require("./user.routes");
const routes = (0, express_1.Router)();
exports.routes = routes;
routes.use(example_routes_1.exampleRoutes);
routes.use("/users", user_routes_1.userRoutes);
